workflows:
  ios-expo-workflow:
    name: iOS Expo Build
    environment:
      vars:
        BUNDLE_ID: "com.remove.help"
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      xcode: latest
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install EAS CLI
        script: |
          npm install -g eas-cli
      - name: Login to Expo
        script: |
          eas login --non-interactive --token $EXPO_TOKEN
      - name: Prebuild iOS project
        script: |
          npx expo prebuild --platform ios --clean
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "com.remove.help" --type IOS_APP_STORE --create
          xcode-project use-profiles
      - name: Build iOS app
        script: |
          xcodebuild -workspace ios/remove.xcworkspace -scheme remove -configuration Release -archivePath build/ios/remove.xcarchive archive
          xcodebuild -exportArchive -archivePath build/ios/remove.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build/ios
    artifacts:
      - build/ios/*.ipa
      - build/ios/*.app
    publishing:
      email:
        recipients:
          - your-email@example.com 